#+INCLUDE: "configuration.org"

# #+SELECT_TAGS: week6
# #+EXPORT_FILE_NAME: answerkey.pdf
#+BEGIN_SRC R :session global :exports none
  include.answer <- FALSE
  seeds <- 1:100
#+END_SRC

* Week #1 :week1:

 1. What is the difference between descriptive and inferential statistics?
 2. Give an example of:
    a. A population and a sample from that population
    b. A parameter and its corresponding statistic
    c. A descriptive research question and an inferential reframing of that question
    d. A research question with an independent variable and a dependent variable
    For each, explain why your example is appropriate.
   
 #+INCLUDE: "./math/summation.org"
 
* Week #2 :week2:

 1. Give an example of:
    a. A discrete variable
    b. A continuous variable
    c. A nominal variable
    d. An ordinal variable
    e. An interval variable
    f. A ratio variable
    For each, explain why your example is appropriate.
 2. Draw a well-designed bar graph and a poorly-designed one, and explain why the first is better
   
 #+INCLUDE: "./math/frequency.org"
 #+INCLUDE: "./math/interval.org"

* Week #3 :week3:

 1. Why is the mean more sensitive to extreme scores than the median?
 2. Give an example of a situation in which we might we prefer the median over the mean
 3. Give an example of a situation in which it would be important to report the variance along with the mean, and justify your answer
 4. What are we squaring in a sum of squares, and why do we do it?
    - $\Sigma[(X_i - \bar{X})^2]$
 5. In what sense is a variance a mean?
    - $\dfrac{\Sigma[(X_i - \bar{X})^2]}{n-1}$
 6. Why do we use $n - 1$ instead of $n$ in the denominator of sample variance?
 7. When would variance be equal to zero? Explain with reference the formula
 8. Why do we use standard deviation instead of variance?
 9. Why is the standard deviation so named?
 10. Is it possible to have a negative standard deviation? Justify your answer with reference to the formula
 11. For the following data set, calculate the mode, median, mean, and standard deviation. Then, add 5 to every number in the data set and calculate again. Then, multiply every number in the data set by 2 and calculate again. What effect does adding/multiplying every score with the same number have, and why? Explain for each statistic.
     - 2, 8, 1, 1, 3
 12. Draw a positively skewed distribution and come up with an example data set to which it might correspond. Then do the same for negative skew

 #+INCLUDE: "./math/median.org"
 #+INCLUDE: "./math/standard_deviation.org"

* Week #4 :week4:

 1. Why do we transform scores into standard scores?
 2. What does the distribution of standard scores look like? Draw it
 3. How does the area under the normal curve tell us about numbers below?
 4. On the first number line below, draw bars representing the frequency distribution of the following data:
    - 4, 6, 4, 3, 8
    Then, subtract the mean from each score and draw the new distribution on the second number line. Then, divide those by the standard deviation and draw them on yet another number line. What does each step do to the distribution?
    
# Number line 1
#+BEGIN_SRC latex
  \vspace{1cm}
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (2.7,0) -- (8.3,0) ;
  \draw[-latex] (2.7,0) -- (8.3,0) ;
  \foreach \x in {3,3.5,...,8}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {3,3.5,...,8}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below] 
  {$\x$};
  \end{tikzpicture}
  \end{center}
  \vspace{0.5cm}
#+END_SRC

# Number line 2
#+BEGIN_SRC latex
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (-2.3,0) -- (3.3,0) ;
  \draw[-latex] (-2.3,0) -- (3.3,0) ;
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below] 
  {$\x$};
  \end{tikzpicture}
  \end{center}
  \vspace{0.5cm}
#+END_SRC

# Number line 3
#+BEGIN_SRC latex
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (-2.3,0) -- (3.3,0) ;
  \draw[-latex] (-2.3,0) -- (3.3,0) ;
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below] 
  {$\x$};
  \end{tikzpicture}
  \end{center}
#+END_SRC

#+INCLUDE: "./math/zscores.org"

* Week #5 :week5:

 1. What is the difference between standard error and standard deviation?
 2. Why is standard error so named?
 3. What is the difference between standard error and standard error of the mean?
 4. What does the standard error of the mean measure?
 5. How do changes in $n$ and \sigma affect $\sigma_{\bar{X}}$? Explain with reference to the formula
    - $\sigma_{\bar{X}} = \dfrac{\sigma}{\sqrt{n}}$
 6. What is the difference between a sampling distribution and a sampling distribution of the mean?
 7. Distinguish between the population distribution, the sample distribution, and the sampling distribution, using an example
 8. Distinguish between the population mean, the sample mean, and the mean of the sampling distribution of the mean, using an example
 9. Imagine a bowl with five bingo chips in it, numbered 1 through 5. For this population:
    a. Calculate the population mean
    b. List all 25 possible samples of size 2
       - Sample with replacement: draw one bingo chip, put it back, and then draw a second
    c. Calculate the mean for every sample
    d. Count the frequency of each value of the sample mean
    e. Calculate the mean of the sampling distribution of the mean
    f. Draw the frequency distribution as a bar plot
    g. Calculate the probability of drawing a sample with:
       - A mean >= 4
       - A mean <= 2.5
       - An error of at least 1.5

* Week #6 :week6:

 1. What are the steps in hypothesis testing? Give an example and relate each step to the concepts we've learned so far in the course (population, sample, parameter, statistic, sampling distribution of the mean, null and alternate hypotheses, critical values, etc.)
 2. Draw a null distribution and illustrate the relationship between the critical values, the rejection region, and \alpha
 3. Draw an alternate distribution and illustrate the relationship between the critical values, the rejection region, \beta, and power
 4. How are \alpha and \beta each affected by change in the critical values, effect size, and standard error?
 5. How do we control Type I and Type II error, respectively? Why don't we make $\alpha = 0$?
 6. $H_0$ and $H_1$ must be exhaustive (one must be true) and mutually exclusive (they can't both be true). Come up with some invalid hypotheses. Here's an example to get you started:
    - $H_0: \mu_1 = \mu_2$
    - $H_1: \mu_1 > \mu_2$
 7. Why do we need hypothesis testing? Why can't we just draw a sample from the population and estimate the parameter by the sample statistic?
 8. Give an example of a finding which is statistically significant but practically insignificant. When might this occur?
 9. What is the goal of a confidence interval?
 10. Give an example of a research question where a nondirectional test would be appropriate, then reframe it so that a directional test would be appropriate

# - What does it mean to say that a /p/ value is a conditional probability?
# - Why is calculating a 1 - \alpha% confidence interval the same as performing a hypothesis test at \alpha?
 
#+INCLUDE: "./math/ztests.org"

* Week #7 :week7:

 1. When should we use a /t/ test instead of a /z/ test?
 2. What is the expected value of /t/ under the null hypothesis?
 3. Why can't we calculate a /t/ statistic with a sample of $n = 1$?
 4. Give an example of a research question for which a one-sample /t/-test would be appropriate, and explain why it is appropriate
 
 #+INCLUDE: "./math/1sample_t-test.org"

* Week #8 :week8:

 1. Give an example of a research question for which you would use an independent /t/-test, and explain why it is appropriate
 2. What is $s_{\bar{X}_1 - \bar{X}_2}$ and what does it measure?
 3. What is homogeneity of variance? State it symbolically
 4. When might we employ a Welch correction?
 5. What is the reasoning behind using pooled variance? Why not simply take the mean of s_1 and s_2?
   
 #+INCLUDE: "./math/independent_t-test.org"

* Week #9 :week9:

 1. Give an example of a research design in which you would use a dependent /t/-test, and explain why it is appropriate
 2. How does using a dependent design rather than an independent design affect power? Why?
 3. Give an example of a research question which could be addressed by ANOVA but not a single t-test
 4. What do the numerator and denominator of the /F/ statistic represent? Why is /F/ is equal to 1 under the null hypothesis?
    - $F = \dfrac{\mathit{MS_B}}{\mathit{MS_W}}$
    - /MS_B/ = "mean squares between"
    - /MS_W/ = "mean squares within"
 5. How much within and between group variability is there in each of the following scenarios?
    - Scenario #1
      - Group 1: [1, 1, 1, 1, 1]
      - Group 2: [1, 1, 1, 1, 1]
      - Group 3: [1, 1, 1, 1, 1]
    - Scenario #2
      - Group 1: [1, 4, 3, 7, 9]
      - Group 2: [2, 3, 4, 8, 8]
      - Group 3: [1, 2, 5, 9, 7]
    - Scenario #3
      - Group 1: [1, 1, 1, 1, 1]
      - Group 2: [15, 15, 15, 15, 15]
      - Group 3: [30, 30, 30, 30, 30]
    - Scenario #4
      - Group 1: [1, 4, 3, 7, 9]
      - Group 2: [15, 26, 17, 29, 21]
      - Group 3: [30, 37, 43, 41, 32]
    Rank them on the likelihoood the null hypothesis ($F = 1$) will be rejected

 #+INCLUDE: "./math/dependent_t-test.org"

* Week #10 :week10:

 1. Give an example of two variables which would have a correlation of close to 1
 2. Give an example of two variables which would have a correlation of close to -1
 3. Give an example of two variables which would have a correlation of close to 0
 4. Draw a a relationship which cannot be accurately described by Pearson's /r/
 5. Why doesn't correlation imply causation? Does causation imply correlation?
 6. Why does $df = n - 2$ when looking up critical /r/ values?
 7. Rank each set of scores as though you were calculating Spearman's rho:
    - 4, 0, 4, 9, 3
    - 3, 5, 3, 6, 3
   
 #+INCLUDE: "./math/pearson.org"

* Week #11 :week11:

 1. What does the regression line minimise? Draw a picture
 2. How many regression lines are possible for a given data set?
 3. Give an example of restriction of range
 4. Explain the difference between a univariate outlier and a regression outlier, and draw a picture
 5. Draw an example of how an influential outlier might affect the regression line
 6. What is a residual and what does it tell us about model fit?

 #+INCLUDE: "./math/regression.org"
