#+INCLUDE: "configuration.org"

# #+SELECT_TAGS: week4
# #+EXPORT_FILE_NAME: answerkey.pdf
#+BEGIN_SRC R :session global :exports none
  include.answer <- TRUE
  seeds <- 1:100
#+END_SRC

* Week #1 :week1:

 1. What is the difference between descriptive and inferential statistics?
 2. Give an example of:
    a. A population and a sample from that population
    b. A parameter and its corresponding statistic
    c. A descriptive research question and an inferential reframing of that question
    d. A research question with an independent variable, a dependent variable, and a confounding variable
    For each, explain why your example is appropriate.
 3. Why is a confounding variable so called? What does it prevent us from doing?

 #+INCLUDE: "./math/summation.org"

* Week #2 :week2:

 1. Give an example of:
    a. A discrete variable
    b. A continuous variable
    c. A nominal variable
    d. An ordinal variable
    e. An interval variable
    f. A ratio variable
    For each, explain why your example is appropriate.
 2. Draw a well-designed bar graph and a poorly-designed one, and explain why the first is better
 3. Why might we prefer:
    a. Relative frequency over frequency?
    b. Cumulative relative frequency over cumulative frequency?

 #+INCLUDE: "./math/frequency.org"
 #+INCLUDE: "./math/interval.org"

* Week #3 :week3:

 1. Why is the mean more sensitive to extreme scores than the median?
 2. Give a scenario in which:
    a. The median would be a better estimate than the mean
    b. The mode would be a better estimate than the median/mean
    c. It would be crucial to report the variance along with the mean
    For each, justify your example.
 3. What are we squaring in a sum of squares, and why do we do it?
    \begin{equation*}
    \Sigma[(X_i - \bar{X})^2]
    \end{equation*}
 4. In what sense is a variance a mean?
    \begin{equation*}
    \dfrac{\Sigma[(X_i - \bar{X})^2]}{n-1}
    \end{equation*}
 5. Why do we use $n - 1$ instead of $n$ in the denominator of sample variance?
 6. When would variance be equal to zero? Explain with reference the formula
 7. Is it possible to have a negative variance? Justify your answer with reference to the formula
 8. Why do we use standard deviation instead of variance?
 9. Why is the standard deviation so named?
 10. For the following data set, calculate the mode, median, mean, and standard deviation. Then, add 5 to every number in the data set and calculate again. Then, multiply every number in the data set by 2 and calculate again. What effect does adding/multiplying every score with the same number have, and why? Explain for each statistic.
     \begin{quote}
     2, 8, 1, 1, 3
     \end{quote}
 11. Draw a positively skewed distribution and identify the approximate location of the mean, median, and mode. Why do they take the order they do?

 #+INCLUDE: "./math/median.org"
 #+INCLUDE: "./math/standard_deviation.org"

* Week #4 :week4:

 1. Last week we saw that
    a. If you subtract the same number from every score, the new mean is the old mean minus that number
    b. If you divide every score by the same number, the new standard deviation is the old standard deviation divided by that number
    So if we subtract the mean from every score, and divide every score by the standard deviation, what are the new mean and standard deviation?
 2. What is the advantage of standard scores over raw scores? Give an example of a scenario in which a standard score would be a lot more meaningful than a raw score
 3. What does the height of the normal curve above a given score tell us about that score? What does the area under the curve for a given interval tell us about that interval?
 4. On the first number line below, draw bars representing the frequency distribution of the following data:
    \begin{quote}
    4, 6, 4, 3, 8
    \end{quote}
    Then, subtract the mean from each score and draw the new distribution on the second number line. Then, divide those by the standard deviation and draw them on the third number line. What does each step do to the location, spread, and shape of the distribution?


# Number line 1
#+BEGIN_SRC latex
  \vspace{1cm}
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (2.7,0) -- (8.3,0) ;
  \draw[-latex] (2.7,0) -- (8.3,0) ;
  \foreach \x in {3,3.5,...,8}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {3,3.5,...,8}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below]
  {$\x$};
  \end{tikzpicture}
  \end{center}
  \vspace{0.5cm}
#+END_SRC

# Number line 2
#+BEGIN_SRC latex
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (-2.3,0) -- (3.3,0) ;
  \draw[-latex] (-2.3,0) -- (3.3,0) ;
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below]
  {$\x$};
  \end{tikzpicture}
  \end{center}
  \vspace{0.5cm}
#+END_SRC

# Number line 3
#+BEGIN_SRC latex
  \begin{center}
  \begin{tikzpicture}[scale=2]
  \draw[latex-] (-2.3,0) -- (3.3,0) ;
  \draw[-latex] (-2.3,0) -- (3.3,0) ;
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,1pt) -- (0pt,-1pt);
  \foreach \x in {-2,-1.5,...,3}
  \draw[shift={(\x,0)},color=black] (0pt,0pt) -- (0pt,-1pt) node[below]
  {$\x$};
  \end{tikzpicture}
  \end{center}
#+END_SRC

#+INCLUDE: "./math/zscores.org"

* Week #5 :week5:

 1. What is the difference between standard error and standard deviation?
 2. Why is standard error so named? What does it measure?
 3. What is the difference between standard error and standard error of the mean?
 4. How do changes in $n$ and \sigma affect $\sigma_{\bar{X}}$? Explain with reference to the formula
    \begin{equation*}
    \sigma_{\bar{X}} = \dfrac{\sigma}{\sqrt{n}}
    \end{equation*}
 5. What is the difference between a sampling distribution and a sampling distribution of the mean?
 6. Distinguish between the population distribution, the sample distribution, and the sampling distribution, using an example
 7. Distinguish between the population mean, the sample mean, and the mean of the sampling distribution of the mean, using an example
 8. Imagine a bowl with five bingo chips in it, numbered 1 through 5. For this population:
    a. Calculate the population mean
    b. List all 25 possible samples of size 2
       \begin{gather*}
       1, 1 \\
       1, 2 \\
       \ \vdots \\
       5, 5
       \end{gather*}
    c. Calculate the mean for every sample
    d. Count the frequency of each value of the sample mean
    e. Calculate the mean of the sampling distribution of the mean
    f. Draw the frequency distribution as a bar plot
    g. Calculate the probability of drawing a sample with:
       - A mean $>=$ 4
       - A mean $<=$ 2.5
       - An error of at least 1.5

* Week #6 :week6:

 1. What are the steps in hypothesis testing? Give an example and relate each step to the concepts we've learned so far in the course (population, sample, parameter, statistic, sampling distribution of the mean, null and alternate hypotheses, critical values, etc.)
 2. Draw a null distribution and illustrate the relationship between the critical values, the rejection region, and \alpha
 3. Draw an alternate distribution and illustrate the relationship between the critical values, the rejection region, \beta, and power
 4. In what sense are \alpha and \beta /conditional/ probabilities?
 5. How are \alpha and \beta each affected by change in the critical values, effect size, and standard error?
 6. How do we control Type I and Type II error, respectively? Why don't we make $\alpha = 0$?
 7. $H_0$ and $H_1$ must be exhaustive (one must be true) and mutually exclusive (they can't both be true). Come up with some invalid hypotheses. Here's an example to get you started:
    \begin{gather*}
    H_0: \mu_1 = \mu_2 \\
    H_1: \mu_1 > \mu_2
    \end{gather*}
 8. Why do we need hypothesis testing? Why can't we just draw a sample from the population and estimate the parameter by the sample statistic?
 9. Give an example of a finding which is statistically significant but practically insignificant. When might this occur?
 10. What is the goal of a confidence interval?
 11. Come up with some research questions for which a nondirectional /z/-test would be appropriate, then reframe them so that a directional test would be appropriate. State the hypotheses formally

# - What does it mean to say that a /p/ value is a conditional probability?
# - Why is calculating a 1 - \alpha% confidence interval the same as performing a hypothesis test at \alpha?

#+INCLUDE: "./math/ztests.org"

* Week #7 :week7:

 1. When should one use a /t/ test instead of a /z/ test?
 2. What is the expected value of $t_{\textnormal{obs}}$ the null hypothesis?
 3. Why can't we calculate $t_{\textnormal{obs}}$ with a sample of $n = 1$?
    \begin{gather*}
    t_{\textnormal{obs}} = \dfrac{\bar{X} - \mu}{s_{\bar{X}}} \\
    s_{\bar{X}} = \dfrac{s}{\sqrt{n}} \\
    s = \dfrac{\Sigma[(X_i - \bar{X})^2]}{n-1}
    \end{gather*}
 4. Come up with some research questions for which a nondirectional one-sample /t/-test would be appropriate, then reframe them so that a directional test would be appropriate. State the hypotheses formally

 #+INCLUDE: "./math/1sample_t-test.org"

* Week #8 :week8:

 1. What is $s_{\bar{X}_1 - \bar{X}_2}$ and what does it measure?
 2. What is homogeneity of variance? State it symbolically
 3. When might we employ a Welch correction?
 4. What is the reasoning behind using pooled variance? Why not simply take the mean of s_1 and s_2?
 5. Come up with some research questions for which a nondirectional independent /t/-test would be appropriate, then reframe them so that a directional test would be appropriate. State the hypotheses formally

 #+INCLUDE: "./math/independent_t-test.org"

* Week #9 :week9:

 1. Come up with some research questions for which a nondirectional dependent /t/-test would be appropriate, then reframe them so that a directional test would be appropriate. State the hypotheses formally
 2. How does using a dependent design rather than an independent design affect power? Why?
 3. Give an example of a research question which could be addressed by ANOVA but not a single t-test
 4. What do the numerator and denominator of the /F/ statistic represent? Why is /F/ is equal to 1 under the null hypothesis?
    \begin{gather*}
    F = \dfrac{\mathit{MS_B}}{\mathit{MS_W}} \\
    \mathit{MS}_B = \textnormal{ "mean squares between"} \\
    \mathit{MS}_W = \textnormal{ "mean squares within"}
    \end{gather*}
 5. How much within and between group variability is there in each of the following scenarios?
    - Scenario #1
      - Group 1: [1, 1, 1, 1, 1]
      - Group 2: [1, 1, 1, 1, 1]
      - Group 3: [1, 1, 1, 1, 1]
    - Scenario #2
      - Group 1: [1, 4, 3, 7, 9]
      - Group 2: [2, 3, 4, 8, 8]
      - Group 3: [1, 2, 5, 9, 7]
    - Scenario #3
      - Group 1: [1, 1, 1, 1, 1]
      - Group 2: [15, 15, 15, 15, 15]
      - Group 3: [30, 30, 30, 30, 30]
    - Scenario #4
      - Group 1: [1, 4, 3, 7, 9]
      - Group 2: [15, 26, 17, 29, 21]
      - Group 3: [30, 37, 43, 41, 32]
    Rank them on the likelihoood the null hypothesis ($F = 1$) will be rejected

 #+INCLUDE: "./math/dependent_t-test.org"

* Week #10 :week10:

 1. Give an example of two variables which would have a correlation of close to 1
 2. Give an example of two variables which would have a correlation of close to -1
 3. Give an example of two variables which would have a correlation of close to 0
 4. Draw a a relationship which cannot be accurately described by Pearson's /r/
 5. Why doesn't correlation imply causation? Give a scenario in which inferring a causal relationship from correlation would be misguided
 6. Why does $df = n - 2$ when looking up critical /r/ values? Explain using a scatterplot of the $n = 2$ and $n = 1$ cases

 #+INCLUDE: "./math/pearson.org"
 #+INCLUDE: "./math/spearman_ranking.org"

* Week #11 :week11:

 1. What does the regression line minimise? Draw a picture
 2. How many regression lines are possible for a given data set?
 3. Give an example of restriction of range
 4. Explain the difference between a univariate outlier and a regression outlier, and draw a picture
 5. Draw an example of how an influential outlier might affect the regression line
 6. What is a residual and what does it tell us about model fit?

 #+INCLUDE: "./math/regression.org"
