\onecolumn
* Week #3 :conceptual:midterm:

Definitions:
 - Mean
 - Median
 - Mode
 - Variance
 - Standard deviation
   
Questions:

 - Why is the mean more sensitive to extreme scores than the median?
 - Why might we prefer the median over the mean?
 - What are we squaring in a sum of squares?
 - What is the point of the squaring in sum of squares?
 - In what sense is a variance a mean?
 - When would variance be equal to zero?
 - Why do we use standard deviation instead of variance?
 - Why do we using $n - 1$ instead of $n$ in the denominator of variance?
 - Why is the standard deviation so named?
 - For the following data set, calculate the mode, median, mean, and standard deviation. Then, add 5 to every number in the data set and calculate again. Then, multiply every number in the data set by 2 and calculate again. What effect does adding/multiplying every score with the same number have, and why? Explain for each statistic.
    \begin{center}
    2, 8, 1, 1, 3
    \end{center}

   
\newpage
   
* Median calculation :ignore:math:midterm:

#+BEGIN_SRC R :session global :results value raw :exports results
printq1 <- dget("./R/median.R")
printq2 <- dget("./R/standard-deviation.R")
print("\\twocolumn")
#+END_SRC

** Median

For each table, calculate the median using this formula:

\begin{equation*}
\mathit{Md} = \mathit{LL} + W \begin{bmatrix} \frac{0.5(n) - \mathit{cumF}}{\mathit{fm}} \end{bmatrix}
\end{equation*}

/LL/ = (score of the row with the lowest CR freq. \geq 0.5) - 0.5

/W/ = interval width (= 1 if the data are ungrouped)

/n/ = sample size (= the highest C freq.)

/cumF/ = CR freq. of the row below the one containing /LL/

/fm/ = frequency of the row containing /LL/

** Question #1
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(TRUE, seeds[1])
#+END_SRC
** Question #2
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[2])
#+END_SRC
** Question #3
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[3])
#+END_SRC
#+BEGIN_SRC R :session global :results value raw :exports results
if (include.answer == TRUE) {
print("\\vfill\\eject")
}
#+END_SRC
** Question #4
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[4])
#+END_SRC
#+BEGIN_SRC R :session global :results value raw :exports results
if (include.answer == FALSE) {
print("\\vfill\\eject")
}
#+END_SRC
** Question #5
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[5])
#+END_SRC
** Question #6
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[6])
#+END_SRC
** Question #7
#+BEGIN_SRC R :session global :results output raw :exports results
printq1(include.answer, seeds[7])
#+END_SRC

\twocolumn


** Standard deviation

\begin{gather*}
\mathit{SS} = \Sigma(X_i - \bar{X})^2 \\
df = n - 1 \\
s^2 = \frac{\mathit{SS}}{df} \\
s = \sqrt{s}
\end{gather*}

** Question #1
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(TRUE, seeds[1])
#+END_SRC
** Question #2
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(include.answer, seeds[2])
#+END_SRC

** Question #3
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(include.answer, seeds[3])
#+END_SRC
** Question #4
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(include.answer, seeds[4])
#+END_SRC
** Question #5
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(include.answer, seeds[5])
#+END_SRC
** Question #6
#+BEGIN_SRC R :session global :results output raw :exports results
printq2(include.answer, seeds[6])
#+END_SRC
